### ISSUE TITLE
Echo_SendCommandByte and Echo_GetStatus write over d1 in Z80 wait loop

### ISSUE THREAD

**Issue by BigEvilCorporation** [sikthehedgehog/Echo#27]
Echo_SendCommandByte and Echo_GetStatus write over d1 (used for parameter value) in Z80 wait loop, resulting in bad status.

**Comment by sikthehedgehog** [comment]
To be more explicit, in the case of `Echo_SendCommandByte` it can result in
an invalid command being sent altogether. It only happens if the queue is
full, which is why it's easy to miss.

I need QA people >_>

**Comment by sikthehedgehog** [comment]
Fixed in 1.61
