### ISSUE TITLE
Extend EEF (PSG instrument) format

### ISSUE THREAD

**Issue by sikthehedgehog** [sikthehedgehog/Echo#8]
Currently the EEF format is quite minimal:

* `$00`~`$0F`: envelope volume values
* `$FE`: start of loop
* `$FF`: end of loop

That leaves 238 possible values (`$10`~`$FD`) completely unused (・＿・；)

On the flipside if you look at Master System and Game Gear games (especially later ones) you'll notice a lot of instruments rely heavily on vibrato. Maybe we could add semitone shifting to EEF instruments, to compensate for PSG being otherwise very limited?

The idea here would be to use `$00`~`$EF` for envelope data. The bottom 4 bits are volume as usual, while the upper 4 bits specify the semitone shifting:

* `$0x`: note as-is
* `$1x`~`$7x`: note shifted up
* `$8x`~`$Ex`: note shifted down

This gives us room for 7 values up and down, would need to see how I want those values to map. Obvious would be ±1,±2,±3,±4,±5,±6,±7 semitones, but not sure how good is that. Some other option would be e.g. ±1,±2,±3,±4,±6,±8,±12 (but no idea if that's too extreme). Comments on this would be nice.

And of course, having to modify Echo to support this...

**Comment by minerscale** [comment]
Hello! On the topic of PSG instruments... Can echo make noise on the PSG channels? It's alright if it doesn't. It sounds awful anyway :p

**Comment by sikthehedgehog** [comment]
The version in MDEM First (which used Echo 0.3) already had support for it, both PSG4-only and PSG3+PSG4 modes :P (Echo doesn't keep track of that, it's up to you to play the correct "notes" on PSG4 to select the mode - this means you can switch at any moment too)

And nah, I wouldn't say it sounds awful, but you need to be very careful with manipulating volume and pitch over time (especially the former). Incidentally, adding pitch support to PSG instruments could help here.

**Comment by minerscale** [comment]
Sorry 'bout this, but I can't find this anywhere... what "Notes" do you write to get noise out the PSG? I assume a "note" is just a glorified way of sending raw data to the PSG or whatever? Anyway appreciate your work man, really do.

**Comment by sikthehedgehog** [comment]
https://github.com/sikthehedgehog/Echo/blob/master/doc/esf.txt#L145
The exact way to generate that event depends on the tool in question.

**Comment by minerscale** [comment]
Ooh ok, I thought this would be in the EEF document. Alright, cool. Thanks
a lot.

**Comment by sikthehedgehog** [comment]
Back on-topic: got a prototype implementation of it. Right now it seems to work but will wait for some more testing first, if I can confirm it isn't a bugfest I'll upgrade Echo (・・　)

**Comment by marcb0t** [comment]
Yes, vibrato is an absolute must for PSG!
I hope you are able to get this going. It is vital to the music I am designing for a really cool game.
You have my full support for this feature!

**Comment by sikthehedgehog** [comment]
So far no playback problems reported so I *think* it works fine. Have been using it for a whistle instrument :P

There are some issues though:

* It doesn't play nice with set frequency events ($3x), so using one of those will disable the semitone shifting until the next note. I guess I may have to include a way for those events to take semitones instead (FM too), less granurality but would let the feature to keep working.

* I still haven't heard from anybody what would be a good range :P Currently the range is 0, ±1, ±2, ±3, ±4, ±6, ±8, ±12 but honestly I have no idea if those >4 values are useful for composers or if they'd prefer different ones.

> Yes, vibrato is an absolute must for PSG!

Note that this is vibrato as part of the instrument... we probably should get vibrato and appregio as events as well (that apply to FM too). It's just that with PSG it's, huuuuh, kind of a must for just about anything meant to sound nice, so baking them into instruments helps (see the whistle thing).

Technically you can already do vibrato with the set frequency events ($3x). It's just that they take up loads of space (3 bytes per channel per tick, so 180 bytes per channel per second x_x). To be fair, MIDI and VGM aren't any better in this respect (VGM is actually *worse*).

**Comment by marcb0t** [comment]
1. I don't mind a little less granularity. To the human ear, "it'll all come out in the wash" as they say. I think our ears would be adequately fooled, and this will be acceptable.

2. I think the values you mention are a good start.

If nothing else, just give it a try and let me or another musician fool around with it. We'll let you know if something doesn't sit well.

3. Yes, arpeggios and vibrato would be very good to have for FM usage as well. There are many times I use vibrato to help give thick chorus, and expressive quality to both my FM and PSG instruments!

4. VGM is absolutely horrible in how it uses vibrato. I'm hoping your method is much more efficient.

**Comment by sikthehedgehog** [comment]
> I don't mind a little less granularity. To the human ear, "it'll all come out in the wash" as they say. I think our ears would be adequately fooled, and this will be acceptable.

I've experimented with this before and even 1/16th of a semitone can be *very* noticeable :/ Depends how fast is the slide. If I could get away with semitone granurality that'd have made things a lot easier since I can just reuse the existing tables.

> If nothing else, just give it a try and let me or another musician fool around with it. We'll let you know if something doesn't sit well.

Nobody wants to cooperate. Instead I get questions about why they should look at Echo (which they consider a horrible format) instead of VGM :P

Also honestly I'm not sure if anybody even understands how this feature works.

**Comment by marcb0t** [comment]
> Nobody wants to cooperate. Instead I get questions about why they should look at Echo (which they consider a horrible format) instead of VGM :P

As I've said, I think VGM is horrible for game designing.

Echo is much more effecient, and requires less data usage per song.

I'm a composer, and I want to cooperate and help you test and implement this feature. Try me. I really want Echo, and I really want vibrato.

Don't worry about other ignorant people out there. You should just make Echo the best homebrew music making option out there.

**Comment by sikthehedgehog** [comment]
Closing this since this is pretty much showing up for the next version.

Also added an alternate version of the set frequency events that should play nice with this extension (albeit at the expense of reduced granurality, which may or may not be an issue depending on the case).

**Comment by minerscale** [comment]
Oh wow, yay!
