### ISSUE TITLE
Tester Rom Doesn't work...

### ISSUE THREAD

**Issue by minerscale** [sikthehedgehog/Echo#9]
So I built the tester rom using this command: asm68k.exe /p tester/build.68k,tester/build.bin

It compiled fine, but the actual music is nowhere to be found.

I just get some annoying beeps

I'll put my compiled rom here:

[build.zip](https://github.com/sikthehedgehog/Echo/files/1184969/build.zip)

**Comment by sikthehedgehog** [comment]
Yeah, I should probably outright remove it altogether (I'm surprised it even builds at all, honestly I'd expect it to complain about missing files). But I need a new tester with means getting good music (for real) which means having good tools so composers actually want to use it...

Consider the tester to be completely dead, I think I even lost some of the files needed to work on it :/

**Comment by minerscale** [comment]
It did complain about missing files. I just pointed it in the right direction :0

Oh, ok then. Nevermind, I wanted something to test it with. But seeing as i'll be using SGDK anyways I don't think it matters that much. Thanks for the engine by the way, appreciate it ;)

**Comment by sikthehedgehog** [comment]
Well, I do have a new tester but there are like only three tracks so I want to get some more first. Besides the lack of good tools is not a good excuse, if anything that should be top priority and cause for shame given that Echo has been around since 2010 and still doesn't have anything decent to compose for it =P

The purpose of the tester was only to check if Echo was working as intended when implementing new features anyway. So it's more of a development sandbox that doubled as a showcase.

**Comment by minerscale** [comment]
Ok. Just one question, is xm2esf the only tool there is to properly develop music for Echo? Not that I'm complaining, it seems pretty good for my means.

**Comment by sikthehedgehog** [comment]
There's midi2esf, mml2esf, dmf2esf (the first two from the mdtools set)... but still nothing is as good as using a dedicated composition tool that generates the right files (OK, DefleMask + dmf2esf may get close).

Composers are not very technical people, they want something that lets them focus on composing. This means instruments sound exactly as on hardware (no approximation with other samples bullshit), the instrument editor is included, also they want access to every effect the hardware could possibly do, etc. Not to mention many of them will probably only want to give you a VGM file and expect you to figure out what to do out of it.

I have a prototype vgm2echo (then just have composers use whatever they want and give you the exported VGM file), though it's still not very advanced. At least results seem to be promising.

**Comment by minerscale** [comment]
Hey, I'm a programmer turned composer... and oh! dmf2esf exists! Alright I'm sold. That vgm2echo sounds very intriguing I hope you get that working properly. Thanks so much for making this and for this conversation. I'll see ya when my game is made with some stunning music.
